language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3

install:
  - pip install .
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - travis_retry pip install coveralls

before_script:
  - travis_retry wget https://github.com/vermaseren/form/releases/download/v4.1-20131025/form-4.1-x86_64-linux.tar.gz
  - tar xvf form-4.1-x86_64-linux.tar.gz
  - export PATH=$PATH:$PWD/form-4.1-x86_64-linux/

script:
  - nosetests --with-doctest --with-coverage --cover-package=form

after_success:
  - coveralls

notifications:
  email: false
