language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

env:
  - FORM_VERSION=4.1

install:
  # Install FORM.
  - |
    case "$FORM_VERSION" in
      4.0-20120410)
      form_url=https://github.com/vermaseren/form/releases/download/v4.0-20120410/form-4.0-20120410-x86_64-linux.tar.gz
        ;;
      4.1)
        form_url=https://github.com/vermaseren/form/releases/download/v4.1-20131025/form-4.1-x86_64-linux.tar.gz
        ;;
    esac
  - travis_retry wget $form_url
  - tar xvf $(basename $form_url)
  - export PATH=$PATH:$(pwd)/$(basename $form_url .tar.gz)
  - form -v | grep -v sec
  # Get installed.
  - pip install .
  # For Coveralls.
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - travis_retry pip install coveralls

script:
  - nosetests --with-doctest --with-coverage --cover-package=form

after_success:
  - coveralls

notifications:
  email: false
