language: python

matrix:
  include:
    # linters
    - python: 2.7
      env: TEST=lint
    - python: 3.7
      env: TEST=lint
    # support for major Python versions
    - python: 2.7
      env: TEST=test FORM_VERSION=4.0
    - python: 2.7
      env: TEST=test FORM_VERSION=4.1
    - python: 2.7
      env: TEST=test FORM_VERSION=4.2
    - python: 2.7
      env: TEST=test FORM_VERSION=4.2.1
    - python: 3.7
      env: TEST=test FORM_VERSION=4.0
    - python: 3.7
      env: TEST=test FORM_VERSION=4.1
    - python: 3.7
      env: TEST=test FORM_VERSION=4.2
    - python: 3.7
      env: TEST=test FORM_VERSION=4.2.1
    # support for minor Python versions
    - python: 2.6
      dist: trusty
      env: TEST=test FORM_VERSION=4.2.1
    - python: 3.2
      dist: trusty
      env: TEST=test FORM_VERSION=4.2.1
    - python: 3.3
      dist: trusty
      env: TEST=test FORM_VERSION=4.2.1
    - python: 3.4
      env: TEST=test FORM_VERSION=4.2.1
    - python: 3.5
      env: TEST=test FORM_VERSION=4.2.1
    - python: 3.6
      env: TEST=test FORM_VERSION=4.2.1
    - python: nightly
      env: TEST=test FORM_VERSION=4.2.1
    - python: pypy
      env: TEST=test FORM_VERSION=4.2.1
    - python: pypy3
      env: TEST=test FORM_VERSION=4.2.1
    # release
    - python: 3.7
      install: skip
      script: skip
      after_success: true
      deploy:
        provider: pypi
        user: "$PYPI_USER"
        password: "$PYPI_PASSWORD"
        distributions: sdist bdist_wheel
        on:
          tags: true
          condition: $TRAVIS_SECURE_ENV_VARS == true
  allow_failures:
    - python: nightly
  fast_finish: true

install: ./scripts/travis.sh install

script: ./scripts/travis.sh script

after_success: ./scripts/travis.sh after_success

notifications:
  email: false
