language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - pypy
  - pypy3

install:
  - pip install .
  - pip install coveralls

before_script:
  - wget https://github.com/vermaseren/form/releases/download/v4.1-20131025/form-4.1-x86_64-linux.tar.gz
  - tar xvf form-4.1-x86_64-linux.tar.gz
  - export PATH=$PATH:$PWD/form-4.1-x86_64-linux/

script:
  - nosetests --with-coverage --cover-package=form

after_success:
  - coveralls

notifications:
  email: false
